# resource_type: user_type
id: 019e3a5c-04ea-7d18-8ae6-f828b1f3d60f
category: user
name: Customer
ouHandle: default
allowSelfRegistration: true
systemAttributes:
  display: username
schema: {
    "username": {
      "type": "string",
      "displayName": "Username",
      "required": true,
      "unique": true
    },
    "password": {
      "type": "string",
      "displayName": "Password",
      "required": false,
      "credential": true
    },
    "email": {
      "type": "string",
      "displayName": "Email",
      "required": true,
      "unique": true,
      "regex": "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"
    },
    "given_name": {
      "type": "string",
      "displayName": "First Name",
      "required": false
    },
    "family_name": {
      "type": "string",
      "displayName": "Last Name",
      "required": false
    },
    "name": {
      "type": "string",
      "displayName": "Full Name",
      "required": false
    },
    "mobile_number": {
      "type": "string",
      "displayName": "Mobile Number",
      "required": false
    }
  }

---
# resource_type: application
id: 2971eb55-7673-4bd0-9ef8-2ed8b53e388f
ouHandle: default
name: sveltekit-quickstart
description: Sample SvelteKit application using the @thunderid/sveltekit SDK
url: http://localhost:5173
logoUrl: emoji:🟠
authFlowHandle: default-basic-flow
isRegistrationFlowEnabled: true
isRecoveryFlowEnabled: false
assertion:
  validityPeriod: 3600
allowedUserTypes:
  - Customer
inboundAuthConfig:
  - type: oauth2
    config:
      clientId: {{.SVELTEKIT_QUICKSTART_CLIENT_ID}}
      redirectUris:
        {{- range .SVELTEKIT_QUICKSTART_REDIRECT_URIS}}
        - {{.}}
        {{- end}}
      grantTypes:
        - authorization_code
      responseTypes:
        - code
      tokenEndpointAuthMethod: client_secret_post
      pkceRequired: true
      publicClient: false
      requirePushedAuthorizationRequests: false
      token:
        accessToken:
          validityPeriod: 3600
          userAttributes:
            - given_name
            - family_name
            - email
            - groups
            - name
        idToken:
          validityPeriod: 3600
          userAttributes:
            - given_name
            - family_name
            - email
            - groups
            - name
          responseType: JWT
      userInfo:
        responseType: JSON
        userAttributes:
          - given_name
          - family_name
          - email
          - groups
          - name
      scopeClaims:
        email:
          - email
          - email_verified
        group:
          - groups
        phone:
          - phone_number
          - phone_number_verified
        profile:
          - name
          - given_name
          - family_name
          - picture

---
# resource_type: server_config
name: cors
value:
  allowedOrigins:
    - "http://localhost:5173"
